basePath: /
host: localhost:8081
info:
  contact:
    email: kliu4403@gmail.com
    name: AutoDeploy Team
  description: 文件上传、部署、Compose、文件管理接口文档
  title: 服务器平台 API 文档
  version: "1.0"
paths:
  /api/v1/files/list:
    get:
      description: 获取指定路径下文件和目录
      parameters:
      - description: 目录路径
        in: query
        name: path
        type: string
      responses: {}
      summary: 获取文件列表
      tags:
      - 文件管理
swagger: "2.0"
